### ISSUE TITLE
Retrieve title of the playlist itself when a playlist url is being used.

### ISSUE THREAD

**Issue by mjcortejo** [rnand/Youtube-downloader#14]
Right now, the title is being retrieved from single videos only. There should be a way to retrieve the title of the playlist when possible. It only returns a blank string in txtfilename.

**Comment by rnand** [comment]
Retrieving the playlist title can be implemented, but what about the individual videos in the playlist? We have two options here:
1. Prompt the user with each title before download
2. Automatically retrieve each title and download without prompting the user.

Right now, the second option is implemented so titles are not displayed on to the text box.

**Comment by mjcortejo** [comment]
Alright, looks like I haven't thoroughly tried out the playlist download yet. Thanks, I'll be trying this out.
